number1 = input("Number1: ")
number2 = input("Number2: ")
print(number1+"+"+number2+" =", int(number1)+int(number2))
print(number1+"-"+number2+" =", int(number1)-int(number2))
print(number1+"*"+number2+" =", int(number1)*int(number2))
print(number1+"/"+number2+" =", int(number1)/int(number2))
